### PR TITLE
Culture view

### PR DESCRIPTION
**Pull request by NickHackman**
Story: [OCA-89](https://5911-capstone.atlassian.net/browse/OCA-89)

## Summary
- [x] Create Culture View
  - [X] MVP
- [X] Fix bugs in Culture API
- [x] Fix bugs in Admin API
- [X] Allow connecting to the API when testing Expo
- [x] Add Admin operations to Culture View
- [X] Improved typing of routes

### MVP:

Still needs a good amount of work:
- Admin operations like editing, creating, deleting content
- Better displaying content, long content now gets cut and it's not clear where admin buttons should go
- Actual admin checking -- this will probably get done further down the road
- Integrate with Home page
- Make it look better on web? I haven't been able to test on mobile but scaling this to mobile it will just look better than the crazy amount of whitespace on web.

## Screenshot(s)

MVP:

windowshot-11-06-2020-12:09:19 AM

windowshot-11-06-2020-12:17:51 AM

### CODE REVIEW

**Comment by NickHackman** [comment]
Sorry this is taking so long, I have the vast majority of functionality done. I should be able to finish it today. I'll update the screenshots when it's finally ready for review.

**Comment by NickHackman** [comment]
All screenshots are using Chrome's emulation of smaller devices. Using the Pixel 2XL. As I can't use Expo to display things on my phone at the moment, need to keep looking into that.

My CSS skills are lacking and without `position: "fixed"` used for CSS, I'm not exactly sure how to display the Floating Action Button at a fixed position on the screen. There are numerous tutorials and stuff for it, but none were helpful. Any insight @freeman91. Otherwhise, overall I think the design is fairly intuitive and is pretty clean for displaying large blobs of text.

New Stories will have to be made for editing Insights, changing the title of a section for a SpecializedInsight, and displaying links (as this can be tricky).

Marking as Ready for Review.

## Screenshots

### View SpecializedInsight
windowshot-11-17-2020-02:15:48 AM

### Edit SpecializedInsight
windowshot-11-17-2020-02:15:54 AM

### Edit SpecializedInsight New Insight
windowshot-11-17-2020-02:15:57 AM

### View GeneralInsights
windowshot-11-17-2020-02:13:53 AM

### Edit GeneralInsights
windowshot-11-17-2020-02:14:12 AM

### Display Admin Editing Tools FABs
windowshot-11-17-2020-02:14:05 AM

**Comment by freeman91** [comment]
This looks great! One question should move some of the components in Culture to their own file?
With the css for the fab button, I will take a look at that and see if I can get it in a fixed position, no promises lol.
Also, what's the problem with not being able to see things on your phone. I think the problem might be because all API requests are using localhost. If you're on your phone both the machine running expo and your phone need to be on the same local network, then API requests should be made to the local ip of your machine, localhost won't work.

**Review by freeman91 — APPROVED** [review]
Looks good!

**Comment by NickHackman** [comment]
@freeman91 I just need to look into it more. I have adb installed and all that to put expo onto the phone, but the issue is that it can connect to the tunnel instance, but it isn't being exposed by my computer. I'll try more on that later today.

> This looks great! One question should move some of the components in Culture to their own file?

I would say yes if any of the components weren't very tightly integrated with the CultureView as a whole, but they probably won't be used in any other place so I don't think it's necessary. If they could be reused yeah that would be ideal.

> With the css for the fab button, I will take a look at that and see if I can get it in a fixed position, no promises lol.

Thanks, I'll keep working on it as well. For sure aggravating that it's so difficult to do something that's really easy in a browser.

**Pull request merged**
